name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and push Docker image JFROG Artifacotry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        IMAGE_TAG: ${{ github.run_id }}
      run: |
        docker login -u $DOCKERHUB_USERNAME myjfrogtestenv.jfrog.io -p $DOCKERHUB_PASSWORD
        docker build -t helloworld-app:${{ env.IMAGE_TAG }} .
        docker tag helloworld-app:${{ env.IMAGE_TAG }} myjfrogtestenv.jfrog.io/docker/helloworld-app:${{ env.IMAGE_TAG }}
        docker push myjfrogtestenv.jfrog.io/docker/helloworld-app:${{ env.IMAGE_TAG }}

    - name: Helm Package
      env:
        HELM_USERNAME: ${{ secrets.HELM_USERNAME }}
        HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
      run: |
        helm registry login https://myjfrogtestenv.jfrog.io/artifactory/api/helm/helm-helm --username ${{ env.HELM_USERNAME }}  --password ${{ secrets.HELM_PASSWORD }}
        helm repo add helm-helm https://myjfrogtestenv.jfrog.io/artifactory/api/helm/helm-helm --username ${{ env.HELM_USERNAME }}  --password ${{ secrets.HELM_PASSWORD }}
        helm package myhelmapp
        curl -u ${{ env.HELM_USERNAME }}:${{ secrets.HELM_PASSWORD }} -T /home/runner/work/myapphelm/myapphelm/myhelmapp-0.1.6.tgz "https://myjfrogtestenv.jfrog.io/artifactory/helm-helm/myhelmapp-0.1.6.tgz"
    # release the package
    - name: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_id }}
        body_path: /home/runner/work/myapphelm/myapphelm/myhelmapp-0.1.6.tgz
        draft: false
        prerelease: false
    - name: publish release
      uses: actions/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: Release ${{ github.run_id }}
        artifact_path: /home/runner/work/myapphelm/myapphelm/myhelmapp-0.1.6.tgz
      
      